# 当前Eureka Server服务的端口号为8761
server:
  port: 8761

#当前Eureka Server的hostname为localhost
eureka:
  instance:
    hostname: localhost
  datacenter: cloud     # Eureka DataCenter的配置
  environment: product  # Eureka Environment的配置
  client:
    #  在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，
    #  所以我们需要禁用它的客户端注册行为。
    #  因为当注册中心将自己作为客户端注册的时候，发现在server上的端口被自己占据了，然后就挂了
    register-with-eureka: false #当前服务不需要到Eureka Server上注册
    fetch-registry: false       # 注册中心的职责就是维护服务实例，因此它并不需要去检索服务，所以设置为false
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/  # 指定服务注册中心的位置

# 追加密码的配置项
#security:
#  user:
#    name: user
#    password: password123