server:
  port: 8040

spring:
  application:
    name: discovery-gateway-zuul
#当前Eureka Server的hostname为localhost
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  datacenter: cloud     # Eureka DataCenter的配置
  environment: product  # Eureka Environment的配置
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/     # 指定服务注册中心的位置

# zuul网关路由映射配置
zuul:
  ignored-services: consumer-movie-ribbon-with-hystrix
  routes:
   provider-user: /user/**


# 追加密码的配置项
#security:
#  user:
#    name: user
#    password: password123