drop TABLE user if EXISTS;

CREATE table USER (
  id bigint not null generated BY DEFAULT AS IDENTITY,
  username VARCHAR(40),
  NAME VARCHAR(20),
  age INT(3),
  balance DECIMAL(10,2),
  PRIMARY KEY(id)
);