server:
  port: 8040

spring:
  application:
    name: discovery-gateway-zuul-fallback
#当前Eureka Server的hostname为localhost
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  datacenter: cloud     # Eureka DataCenter的配置
  environment: product  # Eureka Environment的配置
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/     # 指定服务注册中心的位置

# zuul网关路由映射配置
#zuul:
#  ignored-services: consumer-movie-ribbon-with-hystrix #一种做法将所有微服务进行反向代理，另一中做法是配置指定应用,多个使用逗号分割
#  routes:
#   provider-user: /user/**

zuul:
  #一种做法将所有微服务进行反向代理，另一中做法是配置指定应用名称,多个使用逗号分割
#  ignored-services: consumer-movie-ribbon-with-hystrix
  routes:
  # 路由名称,随意,唯一即可
    users:
      path: /user-path/**  # 路由路径
     # serviceId就是注册到Eureka的serviceId
      serviceId: provider-user
# 追加密码的配置项
#security:
#  user:
#    name: user
#    password: password123